### ISSUE TITLE
TODO: Assignment 1

### ISSUE THREAD

**Issue by MKVO-pts** [samueldatasci/Modelling_biosystems#11]
# Assignment 1
Indice:
- [ ] 1. Data Preparation
    - [x] Plot the data
    - [ ]  Pre-process (if nedded)
        - [ ] 	 Outliers
        - [ ] 	Drift,low freq disturbances
- [ ] 2. System Identification
    - [x] 	ARX with different structures
    - [x] 	Select best models for each case
    - [x] 	Pick one structure and apply it to all datasets
        - [x] 		 determine A and B
        - [ ] 		Calculate SSG and TC
        - [x] 		Pole-zero Diagram
        - [ ] 		Plot: Params vs Athlete* ; Params vs Game *   
        		*kinda done; redo if have time|| Could also use 3D graph
- [ ] 	4. Biological interpretation
    - [x] 		Impose 1st Order Model
    - [ ] 		Impose 2nd Order Model
    - [x] 		Determine average model for each athlete (mean)
    - [x] 		Simulate against real data
- [ ] 5. Time-varying dynamics
    - [x] 	1. Apply a method (Rectangular or Exponential)
        - [x] 		Calculate parameters
        - [x] 		Calculate Metrics of the models
        - [ ] 		Vary the window size or the ###(alpha??)
    - [x] 	2. Plot parameter estimates for all individuals in one figure.
        - [ ] 		Note: Use one subplot for each parameter
