### ISSUE TITLE
TODO: Assignment 2

### ISSUE THREAD

**Issue by MKVO-pts** [samueldatasci/Modelling_biosystems#12]
# Assignment 2
Indice:
- [x] 1. Data Preparation
    - [x] Plot the data
    - [ ]  Pre-process (if nedded)
        - [ ] 	 Outliers
        - [ ] 	Drift,low freq disturbances
- [ ] 2. System Identification
    - [x] 	ARX with different structures
    - [x] 	Select best models for each case (20 models)
    - [ ] 	Pick one structure and apply it to all datasets
        - [x] 		 determine parameters (A and B) 
- [x] 	3. Decompose ARX Modell
    - [x] Explain the model by spliting in **series,parallel, feedback** configurations
    - [ ] Calculate 1st Order Models for each configuration
        - [x] Comment on Stability based on parameters of 1st ord.Models
        - [ ] 	Compare the mathematical decomposition to conclude what is the real model configuration
- [ ] 4. Classification
    - [ ] Based on the characteristics of the Known Cell types Models, classify the unknown models
        - [ ] Use graphs, boxplots, scatter plots, tables,… to classify the data visually
        - [x] Applying a quantitative classification algorithm **(NOT NEEDED - not part of course contents)**

Note: See **_why, how_** and **_for what_** do we need to calculate the _**"Relative standard error"**_ to all parameters (Lecture 9, slide 64)
